
server:
  port: 8080

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  refresh:
    enabled: false

spring:
  datasource:
    dynamic:  #https://github.com/baomidou/dynamic-datasource-spring-boot-starter
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/duckula?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true #mysql5.7以上用useSSL=false
          username: root
          password: mysql  #ENC(xxxxx)  内置加密,使用请查看详细文档
          driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
#        slave_1:
#          url: jdbc:mysql://xx.xx.xx.xx:3307/dynamic
#          username: root
#          password: 123456
#          driver-class-name: com.mysql.jdbc.Driver    
  #解决Error creating bean with name 'scopedTarget.dataSource': Requested bean is currently in creation: Is  
  cloud:
    refresh:
      refreshable: none
mybatis-plus:
  mapper-locations: classpath:mybatis/primary/sqlmap/*.xml        
    

#打印SQL日志
logging:
  level:
    net.wicp.tams.app.duckula.controller.dao: DEBUG    

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 600000
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 600000